# 1.  Tell Travis we need a copy of docker running
sudo: required
language: generic
services:
  - docker

# 2.  Build our image using Dockerfile.dev
before_install:
  - docker build -t philmui/reactcounter -f Dockerfile.dev .

# 3.  Tell Travis how to run our test suite
script:
  - docker run -e CI=true philmui/reactcounter npm run test

# 4.  Tell Travis how to deploy our code to AWS
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "reactcounter"
  env: "Reactcounter-env"
  bucket_name: "elasticbeanstalk-us-east-2-044537394587"
  bucket_path: "reactcounter"
  on:
    branch: main
  access_key_id: $TRAVIS_AWS_ACCESS_KEY
  secret_access_key: $TRAVIS_AWS_SECRET_KEY